language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"

install:
  - pip install nose "textile>=2.1.8" docutils pygments coveralls
  - pip install .

script:
  - coverage run ./setup.py nosetests

after_success:
  coveralls

notifications:
  irc: "irc.freenode.org#pylucid"
