language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"

install:
  - pip install --verbose "textile>=2.1.8" docutils pygments coveralls

script:
  - coverage run ./setup.py test

after_success:
  coveralls

notifications:
  irc: "irc.freenode.org#pylucid"
